### ISSUE TITLE
Vina-GPU runtime error: "./OpenCL/src/kernels/code_head.cpp Error: failed to open file"

### ISSUE THREAD

**Issue by mengruts** [DeltaGroupNJUPT/Vina-GPU#47]
I can successfully build Vina-GPU on Ubuntu 20.04. However when I run Vina-GPU the error happened. 

I re-compiled with -DOPENCL_3_0/-DOPENCL_2_0/-DOPENCL_1_2 in MakeFile, all can be built successfully but got the same runtime error like below. Anyone can help on this?

Using single ligand docking mode

Output will be ./039/cmpd-39_out.pdbqt
Reading input ... done.
Setting up the scoring function ... done.
Using heuristic search_depth
Analyzing the binding site ... done.
GPU Platform: NVIDIA CUDA
GPU Device: Tesla V100-PCIE-16GB
Using random seed: 970523110

Build kernel 1 from sourceError: failed to open file
: ./OpenCL/src/kernels/code_head.cppError: failed to open file
Segmentation fault (core dumped)

Thanks,
Regards,
Raymond,

**Comment by foo1egg** [comment]
I had a similar problem. 
WARNING: The search space volume > 27000 Angstrom^3 (See FAQ)
Using single ligand docking mode

Output will be lig_out.pdbqt
Reading input ... done.
Setting up the scoring function ... done.
Search_depth is fixed to 200
Analyzing the binding site ... done.
GPU Platform: NVIDIA CUDA
GPU Device: NVIDIA GeForce RTX 4090
Using random seed: -564014416

**Build kernel 1 from sourceError: failed to open file
: ./OpenCL/src/kernels/code_head.clError: failed to open file
: ./OpenCL/src/kernels/kernel1.cl**

An error occurred: basic_string::_M_construct null not valid.

**Comment by Glinttsd** [comment]
Hi, please put the `Vina-GPU` executable file in the root dir of Vina-GPU, so that `Vina-GPU` could find the file path (which is `./OpenCL/src/***`)

**Comment by diffracteD** [comment]
I have it installed as a part of sbgrid. Still the same issue persists!
